import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { utils, writeFile } from 'xlsx';

export function exportToCSV(reportData, title) {
    if (!reportData?.details || reportData.details.length === 0) {
        console.error("No data to export for CSV.");
        return;
    }
    const data = reportData.details;
    const headers = Object.keys(data[0]);
    const csvContent = [
        headers.join(','),
        ...data.map(row => headers.map(header => `"${String(row[header] === null || row[header] === undefined ? '' : row[header]).replace(/"/g, '""')}"`).join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `${title.replace(/ /g, '_')}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}

export function exportToPDF(reportData, title, dateRange, generatedBy) {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.text(title, 14, 22);
    doc.setFontSize(10);
    doc.text(`Date Range: ${new Date(dateRange.from).toLocaleDateString()} - ${new Date(dateRange.to).toLocaleDateString()}`, 14, 30);
    doc.text(`Generated by: ${generatedBy}`, 14, 35);
    doc.text(`Generated at: ${new Date().toLocaleString()}`, 14, 40);

    // Summary
    doc.setFontSize(16);
    doc.text('Summary', 14, 55);
    let summaryY = 62;
    doc.setFontSize(12);
    Object.entries(reportData.summary).forEach(([key, value]) => {
        doc.text(`${key}: ${value}`, 14, summaryY);
        summaryY += 7;
    });

    // Details Table
    if (reportData.details && reportData.details.length > 0) {
        const tableColumn = Object.keys(reportData.details[0]);
        const tableRows = reportData.details.map(log => 
            Object.values(log).map(val => String(val !== null && val !== undefined ? val : ''))
        );

        doc.autoTable({
            head: [tableColumn],
            body: tableRows,
            startY: summaryY + 5,
            theme: 'striped',
            headStyles: { fillColor: [22, 160, 133] },
        });
    }

    doc.save(`${title.replace(/ /g, '_')}.pdf`);
}

export function exportToExcel(reportData, title) {
    const summarySheet = utils.json_to_sheet([reportData.summary]);
    const detailsSheet = utils.json_to_sheet(reportData.details);

    const wb = utils.book_new();
    utils.book_append_sheet(wb, summarySheet, "Summary");
    utils.book_append_sheet(wb, detailsSheet, "Details");

    writeFile(wb, `${title.replace(/ /g, '_')}.xlsx`);
}