import React from 'react';

const ReportHeader = ({ title, dateRange, generatedBy }) => {
    return (
        <div className="p-6 bg-[#1E293B] rounded-lg border border-gray-800 mb-6">
            <h2 className="text-2xl font-bold text-white">{title}</h2>
            <div className="flex flex-wrap gap-x-6 gap-y-2 text-sm text-gray-400 mt-2">
                <span>Date Range: {new Date(dateRange.from).toLocaleDateString()} - {new Date(dateRange.to).toLocaleDateString()}</span>
                <span>Generated by: {generatedBy}</span>
                <span>Generated at: {new Date().toLocaleString()}</span>
            </div>
        </div>
    );
};

export default ReportHeader;