import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { format } from 'date-fns';

export const generatePipelinePDF = (caseData, results, charts = {}) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const margin = 15;
  let yPos = 20;

  // Colors
  const brandDark = '#1e293b';
  const brandAccent = '#10b981'; // Emerald for visible text contrast (Lime #BFFF00 is hard to read on white paper)
  const textGrey = '#64748b';

  // --- Header ---
  doc.setFillColor(brandDark);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor('#FFFFFF');
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Pipeline Sizer Report', margin, 20);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Petrolord NextGen Suite', margin, 30);
  
  doc.text(`Date: ${format(new Date(), 'PPpp')}`, pageWidth - margin, 20, { align: 'right' });
  doc.text(`Case: ${caseData.meta?.caseName || 'Untitled'}`, pageWidth - margin, 30, { align: 'right' });

  yPos = 55;

  // --- Case Inputs Summary ---
  doc.setTextColor(brandDark);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('1. Design Basis & Inputs', margin, yPos);
  
  const inputData = [
    ['Fluid Type', caseData.fluidType.toUpperCase(), 'Flow Rate', `${caseData.flowRate} ${caseData.flowUnit}`],
    ['Start Pressure', `${caseData.designParams.startPressure} psi`, 'Start Temp', `${caseData.designParams.startTemp} °F`],
    ['Material', caseData.designParams.material, 'Schedule', `Sch ${caseData.designParams.schedule}`],
    ['Constraints', `Max Vel: ${caseData.constraints.maxVelocity} ft/s`, 'Standard', caseData.constraints.standard]
  ];

  doc.autoTable({
    startY: yPos + 5,
    head: [],
    body: inputData,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 2 },
    columnStyles: { 0: { fontStyle: 'bold', fillColor: '#f1f5f9' }, 2: { fontStyle: 'bold', fillColor: '#f1f5f9' } },
    margin: { left: margin, right: margin }
  });

  yPos = doc.lastAutoTable.finalY + 15;

  // --- Route Segments ---
  doc.text('2. Route Definition', margin, yPos);
  
  const segmentRows = caseData.segments.map((seg, i) => [
    i + 1,
    seg.name,
    `${seg.length} ft`,
    `${seg.elevation} ft`,
    seg.roughness
  ]);

  doc.autoTable({
    startY: yPos + 5,
    head: [['#', 'Segment Name', 'Length', 'Elevation Change', 'Roughness']],
    body: segmentRows,
    theme: 'striped',
    headStyles: { fillColor: brandDark },
    styles: { fontSize: 9 },
    margin: { left: margin, right: margin }
  });

  yPos = doc.lastAutoTable.finalY + 15;

  // --- Results Table ---
  doc.text('3. Sizing Results', margin, yPos);

  const resultRows = results.map(r => [
    `${r.nps}"`,
    r.idInches.toFixed(3),
    r.velocity,
    r.totalDrop,
    r.arrivalPressure,
    r.erosionRatio,
    r.powerKW,
    r.status.toUpperCase()
  ]);

  doc.autoTable({
    startY: yPos + 5,
    head: [['NPS', 'ID (in)', 'Vel (ft/s)', 'dP (psi)', 'Arr P (psi)', 'Erosion', 'Power (kW)', 'Status']],
    body: resultRows,
    theme: 'striped',
    headStyles: { fillColor: brandDark },
    styles: { fontSize: 9, halign: 'center' },
    columnStyles: { 
      7: { fontStyle: 'bold' }
    },
    didParseCell: function(data) {
        if (data.column.index === 7 && data.section === 'body') {
            const val = data.cell.raw;
            if (val === 'PASS') data.cell.styles.textColor = [16, 185, 129];
            else if (val === 'FAIL') data.cell.styles.textColor = [239, 68, 68];
            else data.cell.styles.textColor = [245, 158, 11];
        }
    },
    margin: { left: margin, right: margin }
  });

  yPos = doc.lastAutoTable.finalY + 15;

  // --- Charts (Images) ---
  if (charts.performance) {
    if (yPos + 100 > doc.internal.pageSize.height) {
        doc.addPage();
        yPos = 20;
    }
    doc.text('4. Performance Charts', margin, yPos);
    try {
        doc.addImage(charts.performance, 'PNG', margin, yPos + 5, 180, 80);
        yPos += 90;
    } catch (e) {
        console.warn('Could not add chart image', e);
        doc.setFontSize(8);
        doc.text('(Chart generation failed or blocked)', margin, yPos + 10);
        yPos += 20;
    }
  }

  // --- Footer ---
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(textGrey);
    doc.line(margin, doc.internal.pageSize.height - 15, pageWidth - margin, doc.internal.pageSize.height - 15);
    doc.text(`Generated by Petrolord NextGen • Confidential`, margin, doc.internal.pageSize.height - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, doc.internal.pageSize.height - 10, { align: 'right' });
  }

  return doc;
};