import React from 'react';

export const traceHeaderMap = [
  { key: 'traceSequenceNumber', byte: 1, length: 4, format: 'int32' },
  { key: 'traceSequenceNumberInFile', byte: 5, length: 4, format: 'int32' },
  { key: 'originalFieldRecordNumber', byte: 9, length: 4, format: 'int32' },
  { key: 'traceNumberInOriginalRecord', byte: 13, length: 4, format: 'int32' },
  { key: 'sourcePointNumber', byte: 17, length: 4, format: 'int32' },
  { key: 'ensembleNumber', byte: 21, length: 4, format: 'int32' },
  { key: 'traceNumberInEnsemble', byte: 25, length: 4, format: 'int32' },
  { key: 'traceIdCode', byte: 29, length: 2, format: 'int16' },
  { key: 'numVerticallySummedTraces', byte: 31, length: 2, format: 'int16' },
  { key: 'numHorizontallyStackedTraces', byte: 33, length: 2, format: 'int16' },
  { key: 'dataUse', byte: 35, length: 2, format: 'int16' },
  { key: 'distanceFromSourceToReceiver', byte: 37, length: 4, format: 'int32' },
  { key: 'receiverGroupElevation', byte: 41, length: 4, format: 'int32' },
  { key: 'sourceElevation', byte: 45, length: 4, format: 'int32' },
  { key: 'sourceDepth', byte: 49, length: 4, format: 'int32' },
  { key: 'receiverDatumElevation', byte: 53, length: 4, format: 'int32' },
  { key: 'sourceDatumElevation', byte: 57, length: 4, format: 'int32' },
  { key: 'sourceWaterDepth', byte: 61, length: 4, format: 'int32' },
  { key: 'receiverWaterDepth', byte: 65, length: 4, format: 'int32' },
  { key: 'scalarToElevationsAndDepths', byte: 69, length: 2, format: 'int16' },
  { key: 'scalarToCoordinates', byte: 71, length: 2, format: 'int16' },
  { key: 'sourceX', byte: 73, length: 4, format: 'int32' },
  { key: 'sourceY', byte: 77, length: 4, format: 'int32' },
  { key: 'receiverX', byte: 81, length: 4, format: 'int32' },
  { key: 'receiverY', byte: 85, length: 4, format: 'int32' },
  { key: 'coordinateUnits', byte: 89, length: 2, format: 'int16' },
  { key: 'weatheringVelocity', byte: 91, length: 2, format: 'int16' },
  { key: 'subweatheringVelocity', byte: 93, length: 2, format: 'int16' },
  { key: 'upholeTimeAtSource', byte: 95, length: 2, format: 'int16' },
  { key: 'upholeTimeAtReceiver', byte: 97, length: 2, format: 'int16' },
  { key: 'sourceStaticCorrection', byte: 99, length: 2, format: 'int16' },
  { key: 'receiverStaticCorrection', byte: 101, length: 2, format: 'int16' },
  { key: 'totalStaticApplied', byte: 103, length: 2, format: 'int16' },
  { key: 'lagTimeA', byte: 105, length: 2, format: 'int16' },
  { key: 'lagTimeB', byte: 107, length: 2, format: 'int16' },
  { key: 'delayRecordingTime', byte: 109, length: 2, format: 'int16' },
  { key: 'muteTimeStart', byte: 111, length: 2, format: 'int16' },
  { key: 'muteTimeEnd', byte: 113, length: 2, format: 'int16' },
  { key: 'samplesInTrace', byte: 115, length: 2, format: 'int16' },
  { key: 'sampleIntervalInTrace', byte: 117, length: 2, format: 'int16' },
  { key: 'gainType', byte: 119, length: 2, format: 'int16' },
  { key: 'instrumentGainConstant', byte: 121, length: 2, format: 'int16' },
  { key: 'instrumentInitialGain', byte: 123, length: 2, format: 'int16' },
  { key: 'correlated', byte: 125, length: 2, format: 'int16' },
  // ... and so on for all 240 bytes
];